import type { Category } from '@/core/contracts'

/**
 * 预置 Web 开发规范知识库（规格 9.4）。
 * 全部为自写摘要（非受版权保护原文搬运），每条附来源链接与版本信息。
 * contentHash 由 seed 时按 title+body+sourceUrl 计算。
 */
export interface BuiltinGuideline {
  key: string
  title: string
  category: Category
  tags: string[]
  sourceUrl: string
  sourceVersion: string
  body: string
}

export const BUILTIN_GUIDELINES: BuiltinGuideline[] = [
  /* ---------- 安全（10 条） ---------- */
  {
    key: 'SEC-001',
    title: '避免直接用 innerHTML 写入不可信内容',
    category: 'security',
    tags: ['xss', 'dom', 'innerHTML'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML',
    sourceVersion: 'MDN 2025-06',
    body: 'innerHTML 会把字符串解析为 HTML，一旦内容包含用户输入（评论、昵称、URL 参数），攻击者可注入 script 或事件处理器造成 XSS。需要插入纯文本时使用 textContent；确需富文本时先经过显式白名单净化。审查时注意赋值右侧是否可追溯到外部输入，仅凭出现 innerHTML 不能断言漏洞存在，需确认数据来源。',
  },
  {
    key: 'SEC-002',
    title: 'XSS 防护按上下文转义',
    category: 'security',
    tags: ['xss', 'escape', 'output-encoding'],
    sourceUrl: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html',
    sourceVersion: 'OWASP Cheat Sheet Series 2025',
    body: 'HTML 上下文、属性上下文、JavaScript 上下文和 URL 上下文需要不同的转义规则，混用会导致绕过。React 等框架默认转义插值，但 dangerouslySetInnerHTML、href/src 拼接、内联事件字符串会绕过默认防护。修复建议按输出位置选择对应转义函数或使用框架安全 API。',
  },
  {
    key: 'SEC-003',
    title: 'postMessage 必须指定明确的 targetOrigin',
    category: 'security',
    tags: ['postMessage', 'iframe', 'window'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage',
    sourceVersion: 'MDN 2025-06',
    body: 'window.postMessage 的 targetOrigin 参数写成 "*" 时，任何嵌入该页面的站点都能收到消息内容。应传入具体源（如 https://example.com），除非消息本身不含敏感数据。若目标窗口来源不确定，说明设计上缺少来源约束，应作为待核查问题记录触发条件。',
  },
  {
    key: 'SEC-004',
    title: 'message 事件监听必须校验 event.origin',
    category: 'security',
    tags: ['postMessage', 'message-event', 'origin-check'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event',
    sourceVersion: 'MDN 2025-06',
    body: 'addEventListener("message", ...) 会接收任意来源窗口发来的消息，未校验 event.origin 就使用 event.data 可能被恶意页面伪造指令。正确做法是先比较 origin 与预期的白名单，再处理数据；同源场景也不应省略校验，因为代码可能被复制到跨域环境。',
  },
  {
    key: 'SEC-005',
    title: '禁止 eval 与 new Function 执行动态字符串',
    category: 'security',
    tags: ['eval', 'dynamic-code', 'injection'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval',
    sourceVersion: 'MDN 2025-06',
    body: 'eval、new Function、setTimeout/setInterval 字符串参数会执行任意代码，输入被污染时等同于远程代码执行，且阻碍静态分析与 CSP 防护。替代方案：JSON.parse 解析数据、映射对象替代动态属性名、显式分支替代动态函数体。历史代码迁移时可先标记风险再逐步替换。',
  },
  {
    key: 'SEC-006',
    title: 'dangerouslySetInnerHTML 需配合净化库使用',
    category: 'security',
    tags: ['react', 'xss', 'dangerouslySetInnerHTML'],
    sourceUrl: 'https://react.dev/reference/react-dom/components/common#dangerously-set-innerhtml',
    sourceVersion: 'react.dev 2025',
    body: 'React 中 dangerouslySetInnerHTML 绕过默认转义，官方文档明确要求内容必须经过 DOMPurify 等库净化，且净化配置应限制允许的标签和属性。静态检查只能确认入口存在，需要追踪数据来源后才能定级：内容为常量时风险低，含用户输入且无净化时为高危。',
  },
  {
    key: 'SEC-007',
    title: '不得在源码中硬编码密钥与凭证',
    category: 'security',
    tags: ['secrets', 'credentials', 'git'],
    sourceUrl: 'https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html',
    sourceVersion: 'OWASP Cheat Sheet Series 2025',
    body: 'API Key、数据库密码、Token 提交进仓库后即使删除也会留在历史中，应从环境变量或密钥管理服务读取，.env 文件加入 .gitignore。审查时发现疑似密钥的字符串（长随机串、key/token/secret 命名）应标记为候选，由人工确认；自动化工具报告的是启发式命中，不等于泄露事实。',
  },
  {
    key: 'SEC-008',
    title: '拼接 URL 与打开链接前校验协议',
    category: 'security',
    tags: ['url', 'javascript-protocol', 'open-redirect'],
    sourceUrl: 'https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html',
    sourceVersion: 'OWASP Cheat Sheet Series 2025',
    body: '把用户可控的字符串直接赋给 location.href、window.open 或 a.href，可被注入 javascript: 伪协议脚本或造成开放重定向。处理时应先解析 URL 并白名单校验协议（仅 http/https）与目标域名。仅当拼接来源可被外部控制时才计为风险。',
  },
  {
    key: 'SEC-009',
    title: 'localStorage 不应保存敏感数据',
    category: 'security',
    tags: ['localStorage', 'token', 'storage'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API',
    sourceVersion: 'MDN 2025-06',
    body: 'localStorage 对同源下任何脚本可读，一旦出现 XSS，存储的 Token、个人信息即被窃取，且不受 HttpOnly 保护。会话凭证建议使用 HttpOnly Cookie，非敏感偏好数据才适合放 localStorage。审查时关注存储键名是否包含 token/password/user 等字样，并结合赋值内容判断。',
  },
  {
    key: 'SEC-010',
    title: '理解 Cookie 的 SameSite 与 Secure 属性',
    category: 'security',
    tags: ['cookie', 'csrf', 'samesite'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie',
    sourceVersion: 'MDN 2025-06',
    body: '会话 Cookie 应设置 HttpOnly（防脚本读取）、Secure（仅 HTTPS 传输）与 SameSite=Lax/Strict（缓解 CSRF 与跨站泄露）。SameSite=None 必须配合 Secure。自建会话系统若缺失这些属性，属于系统性缺陷，建议统一封装 Cookie 发放逻辑。',
  },

  /* ---------- 正确性（7 条） ---------- */
  {
    key: 'COR-001',
    title: 'React 列表渲染必须提供稳定 key',
    category: 'correctness',
    tags: ['react', 'list', 'key'],
    sourceUrl: 'https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-keys',
    sourceVersion: 'react.dev 2025',
    body: '列表使用数组索引或不提供 key 时，插入/删除/排序会导致状态与 DOM 错位，输入框内容串行等隐蔽 Bug。key 应来自数据的稳定唯一标识（如 id），不要用 Math.random()。JSX 中 map 返回元素缺失 key 是确定性缺陷；索引 key 仅在列表纯展示且永不重排时可接受。',
  },
  {
    key: 'COR-002',
    title: 'Hook 只能在组件顶层调用',
    category: 'correctness',
    tags: ['react', 'hooks', 'rules-of-hooks'],
    sourceUrl: 'https://react.dev/reference/rules/rules-of-hooks',
    sourceVersion: 'react.dev 2025',
    body: '在条件分支、循环、嵌套函数或 return 之后调用 Hook 会破坏 Hook 调用顺序，导致状态错乱与运行时崩溃。需要条件逻辑时把判断放进 Hook 回调内部（如 useEffect 的 early return 之后再写逻辑需谨慎），或拆分子组件。静态分析只能识别语法层面的条件调用，需人工确认是否在组件或自定义 Hook 顶层。',
  },
  {
    key: 'COR-003',
    title: 'useEffect 依赖数组应完整声明',
    category: 'correctness',
    tags: ['react', 'useEffect', 'dependencies'],
    sourceUrl: 'https://react.dev/reference/react/useEffect',
    sourceVersion: 'react.dev 2025',
    body: '依赖数组缺项会让闭包捕获过期值，出现"读到旧 state"的经典 Bug；故意省略依赖必须注释原因。对象/数组/函数依赖建议用 useMemo/useCallback 稳定化，或在 effect 内组装。exhaustive-deps 规则可自动检出缺失；禁用该规则的代码应视为待核查。',
  },
  {
    key: 'COR-004',
    title: '状态更新保持不可变',
    category: 'correctness',
    tags: ['react', 'immutable', 'state'],
    sourceUrl: 'https://react.dev/learn/updating-objects-in-state',
    sourceVersion: 'react.dev 2025',
    body: '直接 push/splice 修改 state 数组或修改对象属性不会触发重渲染，React 的浅比较检测不到变更。应使用展开运算符、map/filter/concat 等返回新引用的写法。同类问题包括直接修改 useRef.current 指向的对象来驱动渲染。',
  },
  {
    key: 'COR-005',
    title: '异步操作需要处理竞态与取消',
    category: 'correctness',
    tags: ['async', 'race-condition', 'abort'],
    sourceUrl: 'https://react.dev/reference/react/useEffect#fetching-data-with-effects',
    sourceVersion: 'react.dev 2025',
    body: '组件卸载或参数快速变化时，未取消的异步回调仍会 setState，造成内存泄漏警告或旧请求覆盖新数据。应使用 AbortController、ignore 标志或请求序号比对。连续用户输入触发的请求建议防抖。审查时关注 effect 中 fetch 无清理函数的模式。',
  },
  {
    key: 'COR-006',
    title: '限制 TypeScript 中 any 的使用',
    category: 'correctness',
    tags: ['typescript', 'any', 'type-safety'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html',
    sourceVersion: 'TS Handbook 2025',
    body: '显式 any 关闭类型检查，使错误逃逸到运行时并沿调用链扩散。外部数据边界（API 响应、localStorage、URL 参数）应定义类型并用 zod 等校验；确实未知类型可用 unknown 配合类型收窄。`as` 双重断言与 `// @ts-ignore` 属于同类债务。',
  },
  {
    key: 'COR-007',
    title: '空值访问需显式处理',
    category: 'correctness',
    tags: ['typescript', 'null-safety', 'optional-chaining'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html',
    sourceVersion: 'TS Handbook 2025',
    body: '从 Map/数组取值、查找元素、访问可选字段的结果可能为 null/undefined，直接深访问抛出 TypeError。启用 strictNullChecks 并使用可选链与默认值；查找类 API 结果先判空再使用。常见事故点：JSON.parse 结果、document.querySelector、数组 [0]。',
  },

  /* ---------- 性能（6 条） ---------- */
  {
    key: 'PRF-001',
    title: '控制组件重渲染范围',
    category: 'performance',
    tags: ['react', 'rerender', 'memo'],
    sourceUrl: 'https://react.dev/reference/react/memo',
    sourceVersion: 'react.dev 2025',
    body: '父组件重渲染会连带子组件，列表项组件在数据未变时也整树重算。优先把状态下沉到最小使用处；大列表子组件用 memo 包裹并稳定化 props；上下文拆分避免高频值引发全树更新。优化前先用 Profiler 确认瓶颈，避免盲目 memo。',
  },
  {
    key: 'PRF-002',
    title: '长列表使用虚拟化渲染',
    category: 'performance',
    tags: ['virtualization', 'list', 'dom'],
    sourceUrl: 'https://react.dev/reference/react-dom/server/renderToPipeableStream',
    sourceVersion: 'react.dev 2025（性能模式专题）',
    body: '数百条以上的列表全量渲染 DOM 会导致初次渲染与滚动卡顿。使用 react-window / @tanstack/virtual 等虚拟滚动，只渲染可视窗口内的条目。表格类页面还应避免每行内联创建复杂对象与函数。',
  },
  {
    key: 'PRF-003',
    title: 'effect 内高频触发的请求需防抖',
    category: 'performance',
    tags: ['debounce', 'effect', 'network'],
    sourceUrl: 'https://react.dev/learn/you-might-not-need-an-effect',
    sourceVersion: 'react.dev 2025',
    body: '输入框逐字触发搜索/校验请求会打爆服务端并产生竞态。用防抖（如 300ms）或请求序号丢弃过期响应；能合并的请求用批量端点。注意防抖计时器要在 effect 清理时清除。',
  },
  {
    key: 'PRF-004',
    title: '首屏外的图片懒加载',
    category: 'performance',
    tags: ['image', 'lazy-loading', 'lcp'],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading',
    sourceVersion: 'MDN 2025-06',
    body: '首屏图片直接影响 LCP 与带宽，列表页全部立即加载会显著拖慢移动端。原生 loading="lazy" 处理首屏外图片，首屏关键图加 width/height 避免布局抖动，大图用 srcset 适配设备。Next.js 项目优先用 next/image 的自动优化。',
  },
  {
    key: 'PRF-005',
    title: '路由级代码拆分与按需加载',
    category: 'performance',
    tags: ['bundle', 'code-splitting', 'lazy'],
    sourceUrl: 'https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading',
    sourceVersion: 'Next.js Docs 2025',
    body: '把所有页面与重型依赖（图表、编辑器、Markdown 渲染器）打进首包会拉长可交互时间。使用动态 import、React.lazy 或框架路由级拆分，重型组件在首次需要时加载。分析 bundle 构成后再拆，避免过度拆分造成请求碎片化。',
  },
  {
    key: 'PRF-006',
    title: '避免长任务阻塞主线程',
    category: 'performance',
    tags: ['long-task', 'main-thread', 'worker'],
    sourceUrl: 'https://web.dev/articles/optimize-long-tasks',
    sourceVersion: 'web.dev 2025',
    body: '超过 50ms 的同步任务（大数组运算、同步 JSON 序列化、大表格渲染）会阻塞交互与输入响应。分片处理（scheduler.yield / setTimeout）、移入 Web Worker、或用分页/增量渲染。循环内同步 DOM 读写还触发强制回流，应先批量计算再一次写入。',
  },

  /* ---------- 可维护性（7 条） ---------- */
  {
    key: 'MAI-001',
    title: '禁用 @ts-ignore 与 @ts-nocheck',
    category: 'maintainability',
    tags: ['typescript', 'ts-ignore', 'type-checking'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html',
    sourceVersion: 'TS Release Notes 2.6+',
    body: '@ts-ignore 让下一行错误静默通过并随版本升级失效，@ts-nocheck 关闭整个文件的类型检查，都会让类型系统形同虚设。修复方式：解决类型错误、改用 @ts-expect-error 并附 issue 链接注释（错误消失时编译器会提示移除）。存量文件应逐步清理而非整文件豁免。',
  },
  {
    key: 'MAI-002',
    title: '限制 eslint-disable 的范围与原因',
    category: 'maintainability',
    tags: ['eslint', 'disable', 'lint-debt'],
    sourceUrl: 'https://eslint.org/docs/latest/use/configure/rules#disabling-rules',
    sourceVersion: 'ESLint Docs 2025',
    body: 'eslint-disable 无行级范围与说明会让规则永久失效并隐藏新问题。需要豁免时使用行内 disable-next-line 并注明原因；整文件禁用需评审。禁用安全类规则（如 no-eval、react-hooks/exhaustive-deps）应视为高风险信号单独跟踪。',
  },
  {
    key: 'MAI-003',
    title: '导入路径统一：避免多层相对路径',
    category: 'maintainability',
    tags: ['imports', 'path-alias', 'tsconfig'],
    sourceUrl: 'https://www.typescriptlang.org/docs/handbook/module-resolution.html',
    sourceVersion: 'TS Handbook 2025',
    body: '连续三个以上的 ../ 相对导入（../../..）可读性差且重构易错。在 tsconfig 配置 paths 别名（如 @/components）统一引用；移动文件时路径别名不受目录层级影响。注意别名需与构建工具同步配置，未配置的裸别名会构建失败。',
  },
  {
    key: 'MAI-004',
    title: '保持模块单一职责与适度大小',
    category: 'maintainability',
    tags: ['module', 'cohesion', 'file-size'],
    sourceUrl: 'https://web.dev/articles/code-split-behaviors',
    sourceVersion: 'web.dev 2025',
    body: '单个文件混合数据获取、状态管理、UI 与副作用会导致修改影响面不可控。建议按职责拆分：hooks 层、API 层、纯函数工具层、UI 组件层；组件超过约 300 行或包含 5 个以上 effect 时考虑拆分。文件命名与导出命名一致，便于检索。',
  },
  {
    key: 'MAI-005',
    title: '及时清理死代码与未使用依赖',
    category: 'maintainability',
    tags: ['dead-code', 'unused-dependencies', 'bundle-size'],
    sourceUrl: 'https://knip.dev/',
    sourceVersion: 'knip 2025',
    body: '未使用的组件、注释掉的大段代码、只在 package.json 里存在的依赖会增加认知负担与安装体积。使用 knip / ts-prune 检测未导出引用，依赖变更后同步更新 package.json 与锁文件。删除前确认无动态引用（字符串拼接的 import）。',
  },
  {
    key: 'MAI-006',
    title: '移除生产代码中的调试输出',
    category: 'maintainability',
    tags: ['console', 'debugging', 'logs'],
    sourceUrl: 'https://eslint.org/docs/latest/rules/no-console',
    sourceVersion: 'ESLint Rules 2025',
    body: 'console.log 遗留在生产环境会暴露内部结构、影响性能并干扰用户控制台。开发调试输出应通过统一 logger（可按环境关闭），错误路径必须用 console.error 或上报而非静默吞掉。构建时可用插件剥离调试级别输出。',
  },
  {
    key: 'MAI-007',
    title: '用户可见操作需有错误处理与反馈',
    category: 'maintainability',
    tags: ['error-handling', 'ux', 'feedback'],
    sourceUrl: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary',
    sourceVersion: 'react.dev 2025',
    body: '提交、上传、支付等操作的失败若无提示，用户会误以为成功或反复重试。fetch 结果需要处理非 2xx 与网络异常，UI 呈现明确的成功/失败/重试状态；渲染区域配置 ErrorBoundary 防止整页白屏。catch 后仅打印不反馈视为未完成处理。',
  },
]
